### ISSUE TITLE
Store's issue tracker

### ISSUE THREAD

**Issue by duongleh** [duong-le/olympicbooks#1]
- [ ] Carousel on the homepage showing the product list which can be configured in the dashboard
- [x] product, category slug
- [ ] Review, rating
- [ ] After renamed, the name at the top left corner will not change until re-login
